CREATE TABLE STUDENT
(STUDENT_ID INTEGER NOT NULL,
[LAST NAME] VARCHAR(20) NOT NULL,
NAME        VARCHAR(20) NOT NULL,
SURNAME     VARCHAR(20) NOT NULL,
BIRTHDAY    DATETIME    NOT NULL,
ADDRESS_    VARCHAR(60) NOT NULL,
UNIV_ID     INTEGER)

CREATE INDEX STUDENT_ID_INDEX
ON STUDENT(STUDENT_ID)

ALTER TABLE STUDENT
ADD EMAIL VARCHAR(60)

ALTER TABLE STUDENT
ADD CONSTRAINT CHECK_DATE CHECK (BIRTHDAY<getdate())

ALTER TABLE STUDENT
ADD CONSTRAINT STUDENT_STUDENT_ID_UNIQUE UNIQUE (STUDENT_ID)
GO


