CREATE TABLE STUDENT
(STUDENT_ID INTEGER NOT NULL,
[LAST NAME] VARCHAR(20) NOT NULL,
NAME VARCHAR(20) NOT NULL,
SURNAME VARCHAR(20) NOT NULL,
ADDRESS VARCHAR(60) NOT NULL,
BIRTHDAY DATETIME NOT NULL,
UNIV_ID INTEGER NOT NULL)

CREATE TABLE LECTURER
(LECTURER_ID INTEGER NOT NULL,
[LAST NAME] VARCHAR(20) NOT NULL,
NAME VARCHAR(20) NOT NULL,
SURNAME VARCHAR(20) NOT NULL,
ADDRESS VARCHAR(60) NOT NULL,
UNIV_ID INTEGER NOT NULL)

CREATE TABLE SUBJECT
(SUBJ_ID INTEGER NOT NULL,
SUBJ_NAME VARCHAR(20) NOT NULL,
HOUR INTEGER NOT NULL,
SEMESTER INTEGER NOT NULL)

CREATE TABLE UNIVERSITY
(UNIV_ID INTEGER NOT NULL,
UNIV_NAME VARCHAR(20) NOT NULL,
RATING FLOAT NOT NULL,
CITY VARCHAR(20) NOT NULL)

CREATE TABLE EXAM_MARKS
(EXAM_ID INTEGER NOT NULL,
STUDENT_ID INTEGER NOT NULL,
SUBJ_ID INTEGER NOT NULL,
MARK SMALLINT NOT NULL,
EXAM_DATE DATETIME NOT NULL)

CREATE TABLE SUBJ_LECT
(LECTURER_ID INTEGER NOT NULL,
SUBJ_ID INTEGER NOT NULL)

