--Вывести фио студента, оценку, название дисциплины, имя преподавателя. Все оценки выше 3

SELECT DISTINCT STUDENT.SURNAME, STUDENT.NAME, EXAM_MARKS.MARK, SUBJECT.SUBJ_NAME
FROM STUDENT, EXAM_MARKS, SUBJECT, LECTURER
WHERE STUDENT.STUDENT_ID=EXAM_MARKS.STUDENT_ID AND EXAM_MARKS.SUBJ_ID=SUBJECT.SUBJ_ID AND EXAM_MARKS.MARK>3