INSERT INTO STUDENT_5
SELECT *
FROM STUDENT_1
WHERE 1<(SELECT COUNT (EXAM_ID) FROM EXAM_MARKS_1
WHERE ((STUDENT_1.STUDENT_ID=EXAM_MARKS_1.STUDENT_ID) AND (MARK>3) ))

DELETE FROM STUDENT_5

DELETE 
FROM SUBJECT_2
FROM EXAM_MARKS_1
WHERE 0= (SELECT COUNT (MARK) FROM EXAM_MARKS_1
WHERE (SUBJECT_2.SUBJ_ID=EXAM_MARKS_1.SUBJ_ID))

UPDATE STUDENT_5
SET STIPEND=STIPEND+STIPEND*0.2
WHERE 8<=(SELECT SUM(MARK) FROM EXAM_MARKS_1 WHERE (EXAM_MARKS_1.STUDENT_ID=STUDENT_5.STUDENT_ID))

