--свюряъ х пюанрючр б пюгмшу бсгюу

SELECT FIRST.SURNAME, FIRST.UNIV_ID, FIRST.ADDRESS, SECOND.SURNAME, SECOND.UNIV_ID, SECOND.ADDRESS
FROM STUDENT FIRST, LECTURER SECOND
WHERE FIRST.UNIV_ID!=SECOND.UNIV_ID

