CREATE TABLE EXAM_MARKS_2
(EXAM_ID INTEGER,
STUDENT_ID INTEGER,
SUBJ_ID INTEGER,
MARK INTEGER,
EXAM_DATE DATETIME
)

INSERT INTO EXAM_MARKS_2
SELECT *
FROM EXAM_MARKS_1 A
WHERE 3 IN (SELECT MARK 
			FROM EXAM_MARKS_1 B 
			WHERE A.STUDENT_ID=B.STUDENT_ID)
			
DELETE FROM EXAM_MARKS_2

--1<=(SELECT COUNT (SUBJ_ID) MARK FROM EXAM_MARKS_1 WHERE ((EXAM_MARKS_1.STUDENT_ID=EXAM_MARKS_2.STUDENT_ID) AND MARK=3))

--3=(SELECT MARK FROM EXAM_MARKS_1 WHERE (EXAM_MARKS_1.STUDENT_ID=EXAM_MARKS_2.STUDENT_ID))

UPDATE EXAM_MARKS_1
SET MARK=5
WHERE 28705 IN (SELECT SUBJ_ID FROM EXAM_MARKS_1)