SELECT *
FROM STUDENT A
WHERE EXISTS (SELECT RATING 
              FROM UNIVERSITY B 
              WHERE RATING>4 AND A.UNIV_ID=B.UNIV_ID)


------------------------------------------------------------------
SELECT *
FROM STUDENT FIRST
WHERE EXISTS (SELECT RATING 
              FROM UNIVERSITY SECOND
              GROUP BY UNIV_ID, RATING
              HAVING RATING>4 AND FIRST.UNIV_ID=SECOND.UNIV_ID)
------------------------------------------------------------------
SELECT *
FROM STUDENT A
WHERE EXISTS (SELECT UNIV_ID 
              FROM UNIVERSITY B 
              WHERE A.ADDRESS=B.CITY AND A.UNIV_ID!=B.UNIV_ID)
------------------------------------------------------------------
SELECT SUBJ_NAME
FROM SUBJECT FIRST
WHERE EXISTS (SELECT SUBJ_ID
              FROM EXAM_MARKS SECOND
              GROUP BY SUBJ_ID
              HAVING COUNT(DISTINCT STUDENT_ID)>1 AND FIRST.SUBJ_ID=SECOND.SUBJ_ID)


---------------------------------------------------------------------
---------------------------------------------------------------------
SELECT *
FROM EXAM_MARKS
WHERE STUDENT_ID = (SELECT STUDENT_ID FROM STUDENT WHERE SURNAME='Odintsova') 
---------------------------------------------------------------------
SELECT NAME, SURNAME, STUDENT_ID
FROM STUDENT A
GROUP BY STUDENT_ID, NAME, SURNAME 
HAVING 12 IN (SELECT SUBJ_ID FROM EXAM_MARKS B WHERE (A.STUDENT_ID=B.STUDENT_ID))

SELECT NAME, SURNAME, STUDENT_ID
FROM STUDENT
WHERE STUDENT_ID IN (SELECT STUDENT_ID
FROM EXAM_MARKS 
WHERE (MARK > (SELECT AVG(MARK) 
FROM EXAM_MARKS 
WHERE SUBJ_ID = 12 AND STUDENT.STUDENT_ID=EXAM_MARKS.STUDENT_ID))) 
---------------------------------------------------------------------
SELECT NAME, SURNAME, STUDENT_ID
FROM STUDENT
WHERE STUDENT_ID IN (SELECT STUDENT_ID
FROM EXAM_MARKS 
WHERE (MARK < (SELECT AVG(MARK) 
FROM EXAM_MARKS 
WHERE (SUBJ_ID = 54354 AND STUDENT.STUDENT_ID=EXAM_MARKS.STUDENT_ID)))) 

---------------------------------------------------------------------
SELECT COUNT(SUBJ_ID), STUDENT_ID
FROM EXAM_MARKS A
GROUP BY STUDENT_ID
HAVING 1<(SELECT COUNT(SUBJ_ID) FROM EXAM_MARKS B WHERE A.STUDENT_ID=B.STUDENT_ID) 
---------------------------------------------------------------------
SELECT STUDENT_ID, SURNAME, STIPEND
FROM STUDENT S1
WHERE STIPEND=(SELECT MAX(STIPEND) 
               FROM STUDENT S2  
               WHERE S1.ADDRESS=S2.ADDRESS) 
---------------------------------------------------------------------
SELECT STUDENT_ID, SURNAME
FROM STUDENT A
WHERE 0 IN(SELECT COUNT(UNIV_ID) FROM UNIVERSITY B WHERE A.ADDRESS=B.CITY) 
---------------------------------------------------------------------
SELECT DISTINCT SURNAME, STUDENT_ID
FROM STUDENT FIRST, UNIVERSITY SECOND
WHERE FIRST.ADDRESS!=SECOND.CITY AND FIRST.UNIV_ID=SECOND.UNIV_ID

SELECT STUDENT_ID, SURNAME, NAME
FROM STUDENT A
GROUP BY STUDENT_ID, ADDRESS, A.UNIV_ID, SURNAME, NAME
HAVING A.ADDRESS NOT IN (SELECT CITY FROM UNIVERSITY B WHERE A.UNIV_ID=B.UNIV_ID)

