ALTER TABLE STUDENT_4
DROP COLUMN STIPEND

INSERT INTO STUDENT_5
SELECT *
FROM STUDENT_1
WHERE ADDRESS = 'Moscow'

CREATE TABLE STUDENT_5
(STUDENT_ID INTEGER,
[LAST NAME] VARCHAR(20), 
NAME VARCHAR (20),
SURNAME VARCHAR (20),
ADDRESS VARCHAR (60),
BIRTHDAY DATETIME,
UNIV_ID INTEGER,
KURS INTEGER,
STIPEND INTEGER)

INSERT INTO STUDENT_5
SELECT *
FROM STUDENT_1
WHERE UNIV_ID IN (SELECT UNIV_ID FROM UNIVERSITY WHERE CITY='Moscow')

INSERT INTO STUDENT_5
SELECT *
FROM STUDENT_1
WHERE 1<(SELECT COUNT (EXAM_ID) FROM EXAM_MARKS_1
WHERE ((STUDENT_1.STUDENT_ID=EXAM_MARKS_1.STUDENT_ID) AND (MARK>3) ))


ALTER TABLE STUDENT_5
ADD STIPEND INTEGER

UPDATE STUDENT_5
SET STIPEND=STIPEND+STIPEND*0.2
WHERE 8<=(SELECT SUM(MARK) FROM EXAM_MARKS_1 WHERE (EXAM_MARKS_1.STUDENT_ID=STUDENT_5.STUDENT_ID))

DELETE FROM STUDENT_5

DELETE 
FROM SUBJECT_2
FROM EXAM_MARKS_1
WHERE 0= (SELECT COUNT (MARK) FROM EXAM_MARKS_1
WHERE (SUBJECT_2.SUBJ_ID=EXAM_MARKS_1.SUBJ_ID))

CREATE TABLE SUBJECT_2
(SUBJ_ID INTEGER,
[SUBJ NAME] VARCHAR(20),
HOUR INTEGER,
SEMESTER INTEGER, 
)